### ISSUE TITLE
Support Challenge verification

### ISSUE THREAD

**Issue by p4rkrs** [aliforever/gista#3]
Hi,

It would be great to support Challenge Verification like on goinsta, https://github.com/ahmdrz/goinsta/issues/198.

Thanks!

**Comment by aliforever** [comment]
Hi,

Have you tried functions in [challenge.go](https://github.com/aliforever/gista/blob/master/gista-helpers/challenge.go)

**Comment by p4rkrs** [comment]
No sorry, I didn't saw.

Could give an example please? Thanks!

**Comment by aliforever** [comment]
Try this:
```
username, password := "", ""
err = i.Login(username, password, false)
if err != nil {
	switch err.(type) {
	case errs.CheckpointRequired:
		checkPointErr := err.(errs.CheckpointRequired)
		address  := checkPointErr.GetCheckpointUrl()
		cs := gista_helpers.NewChallengeSolver()
		ch, err := cs.GetChallengeByUrl(address)
		if err != nil {
			fmt.Println(err)
			return
		}
		chr, err := cs.GetSolveChallengeByEmail(address, ch.Config.CsrfToken, ch.RollOutHash)
		if err != nil {
			fmt.Println(err)
			return
		}
		reader := bufio.NewReader(os.Stdin)
		fmt.Println((*chr.ExtraData.Content)[1].Text)
		text, _ := reader.ReadString('\n') // Read verification code from terminal
		chsr, err := cs.SolveChallenge(address, ch.Config.CsrfToken, ch.RollOutHash, text)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(chsr)
	return
}
```

**Comment by dying** [comment]
You just rename gista-helpers to helpers, since we can't use "gista-helper" in GoLang code. I'll test this and let you know.

**Comment by dying** [comment]
Thanks! I'll test and let you know.

**Comment by p4rkrs** [comment]
For Challenge, this is correct?

```go
case errs.ChallengeRequired:
			checkPointErr := err.(errs.ChallengeRequired)
			address := checkPointErr.GetChallenge()
			cs := gista_helpers.NewChallengeSolver()
			ch, err := cs.GetChallengeByUrl(address.Url)
			if err != nil {
				fmt.Println(err)
				return
			}
			chr, err := cs.GetSolveChallengeByEmail(address.Url, ch.Config.CsrfToken, ch.RollOutHash)
			if err != nil {
				fmt.Println(err)
				return
			}
			reader := bufio.NewReader(os.Stdin)
			fmt.Println((*chr.ExtraData.Content)[1].Text)
			text, _ := reader.ReadString('\n') // Read verification code from terminal
			chsr, err := cs.SolveChallenge(address.Url, ch.Config.CsrfToken, ch.RollOutHash, text)
			if err != nil {
				fmt.Println(err)
				return
			}
			fmt.Println(chsr)
```

**Comment by aliforever** [comment]
It is correct, let me know if it doesn't work.

**Comment by p4rkrs** [comment]
Hi,

I get this: ![image](https://image.prntscr.com/image/YSatNqetR_GZxXJv61HEFg.png). Do you have the solution? I didn't change anything from the snippet above, expect removing `fmt.Println((*chr.ExtraData.Content)[1].Text)` because it throwed a runtime error.

**Comment by aliforever** [comment]
Does it happen after authorization? 
Since you have entered your code and it's said Authorized.

**Comment by p4rkrs** [comment]
Getting authorization... And authorized is not related to Gista or Instagram. 

I think that the challenge was correctly made since `chsr` return i.instagram.com and CHALLENGE_REDIRECTION.

But after, doing anything with the account throw a runtime error so I guess that it's not logged properly.

**Comment by p4rkrs** [comment]
Do you have any idea whats wrong with my code?

**Comment by aliforever** [comment]
I forgot to mention, you need to re-login after the verification. Repeat the login code after SolveChallenge.

ChallengeSolver works with Instagram web api, Gista works with Instagram Private API. That's why Solver is not built-in and is considered a helper. 

If you still get challenge required error, it's because the instagram account you're trying to log-in to has been logged in with a newer API. You can change these constants to newer API constants or de-activate the account and wait for at least 3 hours, and then login to account using the old constants.
```
IgVersion        = "85.0.0.21.100"
VersionCode      = "146536611"
```

**Comment by p4rkrs** [comment]
```go
case errs.ChallengeRequired:
			checkPointErr := err.(errs.ChallengeRequired)
			address := checkPointErr.GetChallenge()
			cs := gista_helpers.NewChallengeSolver()
			ch, err := cs.GetChallengeByUrl(address.Url)
			if err != nil {
				fmt.Println(err)
				return
			}
			chr, err := cs.GetSolveChallengeByEmail(address.Url, ch.Config.CsrfToken, ch.RollOutHash)
			if err != nil {
				fmt.Println(err)
				return
			}
			reader := bufio.NewReader(os.Stdin)
			fmt.Println((*chr.ExtraData.Content)[1].Text)
			text, _ := reader.ReadString('\n') // Read verification code from terminal
			chsr, err := cs.SolveChallenge(address.Url, ch.Config.CsrfToken, ch.RollOutHash, text)
			if err != nil {
				fmt.Println(err)
				return
			}
			fmt.Println(chsr)
                        ig.login(username, password, false)
```

So I need to end the catch with a login function like this? And thanks, I'll try for the other constants..

**Comment by aliforever** [comment]
Correct, also check for the errors in the second login too. Gista will only work if there are no errors, the nil pointer error you saw was because of that.

**Comment by p4rkrs** [comment]
It worked fine! Thanks.
